// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:0b73942d-379c-43ad-a6fd-fe54007ac98a",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_l3bEklE4u",
    "aws_user_pools_web_client_id": "6kreecquht2osisc7jphqa7v16",
    "oauth": {},
    "aws_mobile_analytics_app_id": "edfbbb33bad14574b3389551323cd6be",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_user_files_s3_bucket": "awsappcreated-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
